pipeline{
    agent { label 'agent-1'}
    environment{
        project = "expense"
    }
    parameters{
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Pick something')
    }
    stages{
        stage('apply'){
            when{
                expression{
                    params.ACTION == 'apply'
                }
            }
                        steps{
                withAWS(credentials: 'aws-creds'){
                    script{
                        sh """
                        cd 50-ecr
                        terraform init -reconfigure
                        terraform plan 
                        terraform apply -auto-approve
                    """
                }
                    
                }
                
            }
        }
        stage('destroy'){
            when{
                expression{
                    params.ACTION == 'destroy'
                }
            }
             steps{
                withAWS(credentials: 'aws-creds'){
                    script{
                        sh """
                        cd 50-ecr
                         
                        terraform destroy -auto-approve
                    """
                }
                    
                }
                
            }
        }

    }
    post{
        always{
            echo "Runs always"
            deleteDir()
        }
        success{
            echo "Runs when build is success"
        }
        failure{
            echo "Runs when build is failed"
        }
        
    }
}