pipeline{
    agent { label 'agent-1'}
    environment{
        project = "expense"
    }
    parameters{
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Pick something')
    }
    stages{
        stage('apply'){
            when{
                expression{
                    params.ACTION == 'apply'
                }
            }
                        steps{
                withAWS(credentials: 'aws-creds'){
                    script{
                        sh """
                        cd 60-acm
                        terraform init -reconfigure
                        terraform plan 
                        terraform apply -auto-approve
                    """
                }
                    
                }
                
            }
        }
        stage('destroy'){
            when{
                expression{
                    params.ACTION == 'destroy'
                }
            }
   steps{
                withAWS(credentials: 'aws-creds'){
                    script{
                        sh """
                        cd 60-acm
                         
                        terraform destroy -auto-approve
                    """
                }
                    
                }
                
            }
        }
        stage('trigger-ingress'){
            when{
                expression{
                    params.ACTION == 'apply'
                }
            }
            steps{
                 build job: '70-ingress', parameters: [string(name: 'ACTION', value: 'apply')], propagate: true
            }
        }
    }
    post{
        always{
            echo "Runs always"
            deleteDir()
        }
        success{
            echo "Runs when build is success"
        }
        failure{
            echo "Runs when build is failed"
        }
        
    }
}