pipeline{
    agent { label 'agent-1'}
    environment{
        project = "expense"
    }
    parameters{
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Pick something')
    }
    stages{
        stage('apply'){
            when{
                expression{
                    params.ACTION == 'apply'
                }
            }
            steps{
                script{
                    sh """
                        echo "terraform init and apply 20-bastion"
                    """
                }
            }
        }
        stage('destroy'){
            when{
                expression{
                    params.ACTION == 'destroy'
                }
            }
            steps{
                script{
                    sh """
                        echo "terraform destroy 20-bastion"
                    """
                }
            }
        }
        stage('trigger-destroy'){
            when{
                expression{
                    params.ACTION == 'destroy'
                }
            }
            stages{
                stage("sg"){
                    steps{
                        build job: '20-bastion', parameters: [string(name: 'ACTION', value: 'destroy')], propogate: true
                    }
                }
                stage("vpc"){
                    steps{
                        build job: '30-rds', parameters: [string(name: 'ACTION', value: 'destroy')], propogate: true
                    }
                }

 
            }

        }

    }
    post{
        always{
            echo "Runs always"
            deleteDir()
        }
        success{
            echo "Runs when build is success"
        }
        failure{
            echo "Runs when build is failed"
        }
        
    }
}