pipeline{
    agent { label 'agent-1'}
    environment{
        project = "expense"
    }
    parameters{
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Pick something')
    }
    stages{
        stage('apply'){
            when{
                expression{
                    params.ACTION == 'apply'
                }
            }
            steps{
                withAWS(credentials: 'aws-creds'){
                    script{
                    sh """
                        cd 20-bastion
                        terraform init -reconfigure
                        terraform plan 
                        terraform apply -auto-approve
                    """
                }
                    
                }
                
            }
        }
        stage('destroy'){
            when{
                expression{
                    params.ACTION == 'destroy'
                }
            }
            steps{
                withAWS(credentials: 'aws-creds'){
                    script{
                        sh """
                        cd 20-bastion
                         
                        terraform destroy -auto-approve
                    """
                }
                    
                }
                
            }
        }
        stage('trigger-destroy'){
            when{
                expression{
                    params.ACTION == 'destroy'
                }
            }
            stages{
                stage("sg"){
                    steps{
                        build job: '10-sg', parameters: [string(name: 'ACTION', value: 'destroy')], propagate: true
                    }
                }
                stage("vpc"){
                    steps{
                        build job: '00-vpc', parameters: [string(name: 'ACTION', value: 'destroy')], propagate: true
                    }
                }

 
            }

        }

    }
    post{
        always{
            echo "Runs always"
            deleteDir()
        }
        success{
            echo "Runs when build is success"
        }
        failure{
            echo "Runs when build is failed"
        }
        
    }
}